# Generated by Django 3.0.2 on 2020-03-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('model', models.FileField(blank=True, null=True, upload_to='model/')),
                ('beam_width', models.IntegerField(blank=True, null=True)),
                ('lm', models.FileField(blank=True, null=True, upload_to='lm/')),
                ('trie', models.FileField(blank=True, null=True, upload_to='trie/')),
                ('lm_alpha', models.IntegerField(blank=True, null=True)),
                ('lm_beta', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
