# Generated by Django 3.0.2 on 2020-03-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lm_alpha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='lm_beta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
