# Generated by Django 3.0.2 on 2020-03-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0002_auto_20200331_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
