# Generated by Django 3.0.2 on 2020-01-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('text', models.CharField(blank=True, max_length=2048, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
