# Generated by Django 3.0.2 on 2020-01-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utterance',
            name='text',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
