# Generated by Django 3.0.2 on 2020-01-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speak', '0004_age_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialect',
            name='detail',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ethnic',
            name='detail',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
    ]
