# Generated by Django 3.0.2 on 2020-02-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speak', '0005_auto_20200130_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='age',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dialect',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ethnic',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
