# Generated by Django 3.0.2 on 2020-02-24 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speak', '0007_auto_20200220_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('audio', models.FileField(upload_to='audio/')),
                ('created_on', models.DateField(auto_now=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speak.Age')),
                ('dialect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speak.Dialect')),
                ('ethnic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speak.Ethnic')),
                ('utterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speak.Utterance')),
            ],
        ),
    ]
