# Generated by Django 3.0.2 on 2020-02-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speak', '0008_voice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='age',
        ),
        migrations.RemoveField(
            model_name='voice',
            name='dialect',
        ),
        migrations.RemoveField(
            model_name='voice',
            name='ethnic',
        ),
        migrations.RemoveField(
            model_name='voice',
            name='utterance',
        ),
    ]
