# Generated by Django 3.0.2 on 2020-02-24 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speak', '0009_auto_20200224_0217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voice',
        ),
    ]
