# Generated by Django 3.0.2 on 2020-02-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speak', '0010_delete_voice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('detail', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
            ],
        ),
    ]
