# Generated by Django 3.0.2 on 2020-02-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speak', '0011_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='detail',
            new_name='category',
        ),
        migrations.AddField(
            model_name='age',
            name='count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dialect',
            name='count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ethnic',
            name='count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
