# Generated by Django 3.0.2 on 2020-03-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speak', '0013_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='name',
        ),
        migrations.AddField(
            model_name='record',
            name='code',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
