# Generated by Django 3.0.2 on 2020-03-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speak', '0014_auto_20200320_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
